# Generated by Django 2.2.4 on 2021-05-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='имя продукта')),
                ('image', models.ImageField(blank=True, upload_to='products_img', verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='цена товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory')),
            ],
        ),
    ]
